[build]
  base = "client"
  command = "npm install --force && npm run build"
  publish = "client/build"

[build.environment]
  REACT_APP_API_URL = "https://wm-stone-logistics-production.up.railway.app/api"
  REACT_APP_ENVIRONMENT = "production"
  GENERATE_SOURCEMAP = "false"
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "https://wm-stone-logistics-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; img-src 'self' data: https:; connect-src 'self' https://wm-stone-logistics-production.up.railway.app;"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"