[build]
  builder = "dockerfile"
  dockerfilePath = "server/Dockerfile"
  dockerContext = "server"

[deploy]
  startCommand = "node server.js"

[[services]]
  protocol = "tcp"
  port = 5000

[healthcheck]
  path = "/health"
  interval = 30
  timeout = 10
  retries = 3