[build]
  builder = "nixpacks"
  buildCommand = "npm install"

[deploy]
  startCommand = "npm start"

[[services]]
  protocol = "tcp"
  port = 5000

[healthcheck]
  path = "/health"
  interval = 30
  timeout = 10
  retries = 3